In [1]:
#%load_ext autoreload
#%autoreload 2
%matplotlib inline
%cd '../HOTS'

/home/laurent/quantic/science/HomeHots/HOTS_clone_laurent/HOTS


In [2]:
import os
import pickle
import datetime
from mix_Network import *

dataset = 'nmnist'
records_path = '../Records'
timestr = datetime.datetime.now().date().isoformat()
timestr = '2020-12-21'
verbose = True

%mkdir -p ../Records
%mkdir -p ../Records/EXP_03_NMNIST

homeo = True
sigma = None
pooling = False
homeinv = False
jitter = False
tau = 5
krnlinit = 'first'
nblay = 3
nbclust = 4

ds = 5
nb_train = 7500//ds
nb_test = 2500//ds

In [3]:
def get_nmnist(NbTrainingData, NbTestingData):
    def loadev(nbdigit, loader, learningset):
        timout = []
        xout = []
        yout = []
        polout = []
        labout = []
        for i in range(NbTrainingData):
            events, target = next(iter(loader))
            for iev in range(events.shape[1]):
                    timout.append(events[0][iev][learningset.ordering.find("t")].item())
                    xout.append(events[0][iev][learningset.ordering.find("x")].item())
                    yout.append(events[0][iev][learningset.ordering.find("y")].item())
                    polout.append(events[0][iev][learningset.ordering.find("p")].item())
                    labout.append(target.item())

        eventsout = [xout,yout,timout,polout,labout,learningset.sensor_size,2]
        return eventsout
    
    learningset = tonic.datasets.NMNIST(save_to='../Data/',
                                    train=False,
                                    transform=None)
    loader = tonic.datasets.DataLoader(learningset, shuffle=True)
    
    events_train = loadev(NbTrainingData, loader, learningset)
    events_test = loadev(NbTestingData, loader, learningset)
    
    return events_train, events_test

#### Building matrix for logistic regression
def gather_data(events_in,
                tau_cla=150, # characteristic time of a digit
                sample_events=50, sample_space = 1,
                verbose=False, debug=False):
    tau_cla *= 1e3 # to enter tau in ms
    n_events = len(events_in[0])

    c_int = lambda n, d : ((n - 1) // d) + 1
    
    data = np.zeros((c_int(events_in[-2][0], sample_space),
                     c_int(events_in[-2][1], sample_space),
                     events_in[-1])) #tmp data

    X = np.zeros((c_int(n_events, sample_events), len(data.ravel())))
    y = np.zeros((c_int(n_events, sample_events), ))

    for i_event in range(1, n_events):
        if events_in[2][i_event]<events_in[2][i_event-1]:
            data = np.zeros((c_int(events_in[-2][0], sample_space),
                     c_int(events_in[-2][1], sample_space),
                     events_in[-1])) #tmp data 

        data *= np.exp(-(events_in[2][i_event]-events_in[2][i_event-1])/tau_cla)
        
        x_pos = events_in[0][i_event]//sample_space
        y_pos = events_in[1][i_event]//sample_space
        p = events_in[3][i_event]
        data[int(x_pos), int(y_pos), int(p)] = 1.

        if i_event % sample_events == sample_events//2 :
            if debug:
                print(f'DEBUG {i_event} {i_event//sample_events} ')
                print(f'DEBUG {y[i_event//sample_events]}   ')
                print(f'DEBUG  {events_in[-3][i_event]} ')
            X[i_event//sample_events, :] = data.ravel()
            y[i_event//sample_events] = events_in[-3][i_event]
            
    if verbose: print('Number of events: ' + str(X.shape[0])+' - Number of features: ' + str(X.shape[1]))
    
    # one hot encoding
    #y_out = np.zeros([y.shape[0],int(max(y)+1)])
    #for i in range(y.shape[0]):
    #    y_out[i,int(y[i])]=1
    
    return X, y#_out

def get_events(tau, krnlinit, nblay, nbclust, homeo, records_path, timestr, dataset, sigma, homeinv, jitter, nb_train, nb_test):
    hotshom = network(krnlinit=krnlinit, tau=tau, nblay=nblay, nbclust=nbclust, homeo=homeo, sigma=sigma, homeinv=homeinv, jitter=jitter)
    arch = [hotshom.L[i].kernel.shape[1] for i in range(len(hotshom.L))]
    fname = f'{records_path}/EXP_03_NMNIST/{timestr}_hots_{dataset}_{arch}_{tau}_{homeo}_{sigma}_{homeinv}_{jitter}'
    print(fname)
    if not os.path.isfile(fname+'_model.pkl'):
        loaderhom, order = hotshom.learning1by1(dataset=dataset)
        with open(fname+'_model.pkl', 'wb') as file:
            pickle.dump([hotshom, loaderhom, order], file, pickle.HIGHEST_PROTOCOL)
    else:
        with open(fname+'_model.pkl', 'rb') as file:
            hotshom, loaderhom, order = pickle.load(file)
            
    if not os.path.isfile(fname+f'_evout_{nb_train}_{nb_test}.pkl'):       
        _, loaderhom, out_train = hotshom.running(loaderhom, order, nb_digit = nb_train, LR=True)
        _, loaderhom, out_test = hotshom.running(loaderhom, order, nb_digit = nb_test, LR=True)
        with open(fname+f'_evout_{nb_train}_{nb_test}.pkl', 'wb') as file:
            pickle.dump([out_train, out_test], file, pickle.HIGHEST_PROTOCOL)
    else:
        with open(fname+f'_evout_{nb_train}_{nb_test}.pkl', 'rb') as file:
            out_train, out_test = pickle.load(file)
    return out_train, out_test


# ### Performing logistic regression
#
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegressionCV.html
#

# from sklearn.linear_model import LogisticRegression as LR
#from sklearn.linear_model import LogisticRegressionCV as LR
# 
opts_LR = dict(max_iter=2000, # random_state=0,
               n_jobs=-1, class_weight='balanced')
#opts_LR['Cs'] = 5
opts_LR['Cs'] = 32
# TODO for a publication use 100 from 10^{-10} to 10

#from sklearn.model_selection import train_test_split

def tic():
    global ttic
    ttic = time.time()
def toc():
    print(f'Done in {time.time() - ttic:.3f} s')

In [4]:
import torch
from torch.utils.data import TensorDataset, DataLoader
torch.set_default_tensor_type("torch.DoubleTensor") # -> torch.tensor([1.2, 3]).dtype = torch.float64
criterion = torch.nn.NLLLoss(reduction="mean") # loss divided by output size
# https://sebastianraschka.com/faq/docs/pytorch-crossentropy.html
class LogisticRegressionModel(torch.nn.Module):
    #torch.nn.Module -> Base class for all neural network modules
    def __init__(self, N, n_classes, bias=True):
        super(LogisticRegressionModel, self).__init__() 
        self.linear = torch.nn.Linear(N, n_classes, bias=bias)
        self.nl = torch.nn.LogSoftmax(dim=1)

    def forward(self, factors):
        return self.nl(self.linear(factors))

In [5]:
learning_rate = 0.005
beta1, beta2 = 0.9, 0.999
betas = (beta1, beta2)
num_epochs = 2 ** 9 + 1
batch_size = 256
n_classes=10
amsgrad = False # gives similar results
amsgrad = True  # gives similar results

def fit_data(factors, y, 
            learning_rate=learning_rate,
            batch_size=batch_size,  # gamma=gamma,
            num_epochs=num_epochs,
            betas=betas,
            verbose=False, **kwargs
        ):

    # print(factors.shape, y.shape)
    X, labels = torch.Tensor(factors), torch.Tensor(y).to(torch.long)
    # print(X.shape, labels.shape)
    loader = DataLoader(
        TensorDataset(X, labels), batch_size=batch_size, shuffle=True
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f'device -> {device}')
    
    N_batch = factors.shape[0]
    N = factors.shape[1]
    n_classes = 10 # y.shape[1]
    logistic_model = LogisticRegressionModel(N, n_classes)
    logistic_model = logistic_model.to(device)
    logistic_model.train()
    optimizer = torch.optim.Adam(
        logistic_model.parameters(), lr=learning_rate, betas=betas, amsgrad=amsgrad
    )
    for epoch in range(int(num_epochs)):
        logistic_model.train()
        losses = []
        for X_, labels_ in loader:
            X_, labels_ = X_.to(device), labels_.to(device)
            outputs = logistic_model(X_)
            #target = torch.argmax(torch.squeeze(labels_,dim=1), 1)
            loss = criterion(outputs, labels_)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            losses.append(loss.item())

        if verbose and (epoch % (num_epochs // 32) == 0):
            print(f"Iteration: {epoch} - Loss: {np.mean(losses):.5f}")
            
    return logistic_model, losses

In [6]:
tic()
events_train, events_test = get_nmnist(nb_train, nb_test)
toc()

Using downloaded and verified file: ../Data/nmnist_test.zip
Extracting ../Data/nmnist_test.zip to ../Data/
Done in 294.104 s


In [7]:
tic()
X_train, y_train = gather_data(events_train, verbose=verbose)
toc()

Number of events: 125828 - Number of features: 2312
Done in 29.583 s


In [8]:
y_train

array([7., 7., 7., ..., 6., 6., 6.])

In [9]:
N = X_train.shape[1]

logistic_model = LogisticRegressionModel(N, n_classes)

logistic_model, losses = fit_data(X_train, y_train, verbose=True)
# print("Final mean loss =", np.mean(losses))

device -> cuda
Iteration: 0 - Loss: 0.30670
Iteration: 16 - Loss: 0.01301
Iteration: 32 - Loss: 0.00834
Iteration: 48 - Loss: 0.00636
Iteration: 64 - Loss: 0.00522
Iteration: 80 - Loss: 0.00445
Iteration: 96 - Loss: 0.00390
Iteration: 112 - Loss: 0.00349
Iteration: 128 - Loss: 0.00316
Iteration: 144 - Loss: 0.00290
Iteration: 160 - Loss: 0.00267
Iteration: 176 - Loss: 0.00248
Iteration: 192 - Loss: 0.00232
Iteration: 208 - Loss: 0.00219
Iteration: 224 - Loss: 0.00206
Iteration: 240 - Loss: 0.00195
Iteration: 256 - Loss: 0.00185
Iteration: 272 - Loss: 0.00177
Iteration: 288 - Loss: 0.00169
Iteration: 304 - Loss: 0.00161
Iteration: 320 - Loss: 0.00156
Iteration: 336 - Loss: 0.00149
Iteration: 352 - Loss: 0.00143
Iteration: 368 - Loss: 0.00138
Iteration: 384 - Loss: 0.00133
Iteration: 400 - Loss: 0.00129
Iteration: 416 - Loss: 0.00125
Iteration: 432 - Loss: 0.00121
Iteration: 448 - Loss: 0.00117
Iteration: 464 - Loss: 0.00114
Iteration: 480 - Loss: 0.00111
Iteration: 496 - Loss: 0.00108
I

In [10]:
def predict_data(factors, y, model,
            batch_size=batch_size,  # gamma=gamma,
            verbose=False, **kwargs
        ):
    X = torch.Tensor(factors)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f'device -> {device}')

    logistic_model = model.to(device)
    
    X = X.to(device)
    outputs = logistic_model(X)

    pred_target = torch.argmax(outputs, dim=1)
    
    return pred_target

In [11]:
X_test, y_test = gather_data(events_test, verbose=verbose)
pred_target = predict_data(X_test, y_test, logistic_model)

Number of events: 126801 - Number of features: 2312
device -> cuda


In [12]:
y_test


array([7., 7., 7., ..., 3., 3., 3.])

In [13]:
pred_target

tensor([7, 7, 7,  ..., 3, 3, 3], device='cuda:0')

In [14]:
pred_target.detach().numpy() 

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [15]:
pred_target.detach().numpy() == y_test

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [16]:
np.mean(pred_target.detach().numpy() == y_test)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [17]:
print(f'Accuracy = {np.mean(pred_target.detach().numpy() == y_test)*100:.1f}%')

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [18]:
events_train_o, events_test_o = get_events(tau, krnlinit, nblay, nbclust, homeo, records_path, timestr, dataset, sigma, homeinv, jitter, nb_train, nb_test)
X_train, y_train = gather_data(events_train_o, verbose=verbose)

../Records/EXP_03_NMNIST/2020-12-21_hots_nmnist_[4, 8, 16]_5_True_None_False_False


AttributeError: 'TimeSurface' object has no attribute 'decay'

In [19]:
n_classes = 10
N = X_train.shape[1]

logistic_model = LogisticRegressionModel(N, n_classes)

logistic_model, loss = fit_data(X_train, y_train, verbose=True)
print("Final loss =", loss)

device -> cuda
Iteration: 0 - Loss: 0.30643
Iteration: 16 - Loss: 0.01286
Iteration: 32 - Loss: 0.00821
Iteration: 48 - Loss: 0.00627
Iteration: 64 - Loss: 0.00513
Iteration: 80 - Loss: 0.00439
Iteration: 96 - Loss: 0.00384
Iteration: 112 - Loss: 0.00343
Iteration: 128 - Loss: 0.00311
Iteration: 144 - Loss: 0.00284
Iteration: 160 - Loss: 0.00263
Iteration: 176 - Loss: 0.00244
Iteration: 192 - Loss: 0.00228
Iteration: 208 - Loss: 0.00215
Iteration: 224 - Loss: 0.00202
Iteration: 240 - Loss: 0.00192
Iteration: 256 - Loss: 0.00182
Iteration: 272 - Loss: 0.00173
Iteration: 288 - Loss: 0.00166
Iteration: 304 - Loss: 0.00159
Iteration: 320 - Loss: 0.00152
Iteration: 336 - Loss: 0.00146
Iteration: 352 - Loss: 0.00141
Iteration: 368 - Loss: 0.00136
Iteration: 384 - Loss: 0.00131
Iteration: 400 - Loss: 0.00127
Iteration: 416 - Loss: 0.00123
Iteration: 432 - Loss: 0.00119
Iteration: 448 - Loss: 0.00115
Iteration: 464 - Loss: 0.00112
Iteration: 480 - Loss: 0.00109
Iteration: 496 - Loss: 0.00106
I

In [20]:
X_test, y_test = gather_data(events_test_o, verbose=verbose)
pred_target = predict_data(X_test, y_test, logistic_model)

NameError: name 'events_test_o' is not defined